// src/pages/_app.tsx
import "../styles/globals.scss";
import type { AppType } from "next/app";
import { trpc } from "../utils/trpc";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return <div>
    <Head>
      <title>Pharmacocinetique</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="min-h-screen w-screen flex-col bg-red-50 items-between justify-between">
      <Component {...pageProps} />
    </main>
  </div>
};

export default trpc.withTRPC(MyApp);
